export {default as HomeLayout} from "./HomeLayout"
export {default as Landing} from "./Landing" 
export {default as Error} from "./Error" 
export {default as About} from "./About" 
export {default as Services} from "./Services" 
export {default as Contact} from "./Contact" 